/*
Álvaro Domingues de Freitas     Matrícula: 201876007
 */
package Interface;

import javax.swing.JOptionPane;
import Perfis.*;
import Programa.*;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tpalvaro -- Janela principal, onde tudo é executado
 */
public class Principal extends javax.swing.JFrame {
    
    ConjuntoSeries series;
    ConjuntoPerfis perfis;
    Perfil perfil;
    Perfil perfilAtivo;
    Serie serie;
    Episodio ep;
    Temporada temp;
    BancoDePerfis bancoP;
    BancoDeSeries bancoS;

    /**
     * Creates new form JanelaLogin
     */
    public Principal() {
        initComponents();
        series = new ConjuntoSeries();
        perfis = new ConjuntoPerfis();
        bancoP = new BancoDePerfis(perfis);
        bancoS = new BancoDeSeries(series);

        try {
            perfis = bancoP.pegaArquivo();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        imprimeTabela(perfis, jTable1);
        try {
            series = bancoS.pegaArquivo();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        imprimeTabelaSeries(series, jTable2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botaoAddPerfil = new javax.swing.JButton();
        labelNick = new javax.swing.JLabel();
        labelNome = new javax.swing.JLabel();
        labelNumSeries = new javax.swing.JLabel();
        labelNumEps = new javax.swing.JLabel();
        labelNumHoras = new javax.swing.JLabel();
        labelBio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        curioLivro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        curioFilme = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        curioCalorias = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botaoExcluiPerfil = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplicação Java");
        setResizable(false);

        botaoAddPerfil.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botaoAddPerfil.setText("ADICIONAR PERFIL");
        botaoAddPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAddPerfilActionPerformed(evt);
            }
        });

        labelNick.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelNick.setText("Nenhum Perfil Ativo");

        labelNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelNome.setText("-");

        labelNumSeries.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNumSeries.setText("-");

        labelNumEps.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNumEps.setText("-");

        labelNumHoras.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelNumHoras.setText("-");

        labelBio.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelBio.setText("-");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("Enquanto Isso...");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setText("Esse tempo é equivalente a: ");

        jLabel10.setText("Ler um livro de");

        curioLivro.setText("-");

        jLabel2.setText("páginas.");

        jLabel3.setText("Ver toda a Saga Senhor dos Anéis");

        curioFilme.setText("-");

        jLabel5.setText("vezes.");

        jLabel6.setText("Queimar");

        curioCalorias.setText("-");

        jLabel11.setText("calorias em caminhadas.");

        botaoLogin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botaoLogin.setText("ENTRAR");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNumEps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNumHoras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelBio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNumSeries, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelNick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAddPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addGap(168, 168, 168)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(curioFilme, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(curioLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(botaoLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(curioCalorias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel11))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNick, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(curioLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNumSeries, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curioFilme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNumEps, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(curioCalorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelBio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAddPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane5.addTab("PERFIL", jPanel1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nickname", "Num. Séries"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        botaoExcluiPerfil.setText("EXCLUIR PERFIL");
        botaoExcluiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluiPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoExcluiPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoExcluiPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("PERFIS", jPanel4);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Numero de Episodios", "Numero de Seguidores", "Numero de Estrelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 158, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("SÉRIES", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jTabbedPane5.addTab("ADICIONAR SÉRIES", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAddPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAddPerfilActionPerformed
        
        
        boolean existe = false;
        String nick = JOptionPane.showInputDialog("Digite o Nickname: ");
        for (int i = 0; i < (perfis.listaPerfis().size()); i++) {
            if (nick.equals(perfis.getPerfil(i).getNick())) {
                JOptionPane.showMessageDialog(null, "Ja existe um perfil com esse Nickname.");
                existe = true;
                break;
            }
        }
        if(!existe){
            if(nick.equals("")){
                JOptionPane.showMessageDialog(null, "O nickname não pode ser vazio.");
            }else{
                String nome = JOptionPane.showInputDialog("Digite o seu nome completo: ");
                String bio = JOptionPane.showInputDialog("Digite um pouco sobre você: ");
                String senha = JOptionPane.showInputDialog("Digite uma senha: ");
                perfil = new Perfil(nome, nick, bio, senha);
                perfis.addPerfil(perfil);
                atualizaJson(perfis);
                atualizaTabela(perfis,jTable1);
                JOptionPane.showMessageDialog(null, "O perfil foi criado.");
            }
        
        } 
    }//GEN-LAST:event_botaoAddPerfilActionPerformed

    private void botaoExcluiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluiPerfilActionPerformed
        
        String nick = JOptionPane.showInputDialog("Digite o Nickname da Conta que deseja remover: ");
        for(int i = 0;i<perfis.listaPerfis().size();i++){
            if(nick.equals(perfis.listaPerfis().get(i).getNick())){
                String senha = JOptionPane.showInputDialog("Digite a senha: ");
                if(senha.equals(perfis.listaPerfis().get(i).getSenha())){
                    perfis.listaPerfis().remove(i);
                    JOptionPane.showMessageDialog(rootPane,"Perfil Excluido");
                    atualizaJson(perfis);
                    
                    atualizaTabela(perfis, jTable1);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "A senha nao corresponde ao perfil requirido.");
                }
            }
        }
        
        
        
    }//GEN-LAST:event_botaoExcluiPerfilActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        String nick = JOptionPane.showInputDialog("Digite o Nickname da Conta com a qual quer logar: ");
        for(int i = 0;i<perfis.listaPerfis().size();i++){
            if(nick.equals(perfis.listaPerfis().get(i).getNick())){
                String senha = JOptionPane.showInputDialog("Digite a senha: ");
                if(senha.equals(perfis.listaPerfis().get(i).getSenha())){
                    perfilAtivo = perfis.listaPerfis().get(i);
                    JOptionPane.showMessageDialog(rootPane, "Bem-vindo de volta, "+perfilAtivo.getNick());
                    labelNome.setText(perfilAtivo.getNome());
                    labelNick.setText(perfilAtivo.getNick());
                    labelBio.setText(perfilAtivo.getBio());
                    labelNumHoras.setText(Integer.toString(perfilAtivo.getNumHoras()));
                    labelNumEps.setText(Integer.toString(perfilAtivo.getNumEps()));
                    labelNumSeries.setText(Integer.toString(perfilAtivo.getSeriesAssistidas().size()));
                }else{
                    JOptionPane.showMessageDialog(rootPane, "A senha nao corresponde ao perfil requirido.");
                }
                
            }
    }//GEN-LAST:event_botaoLoginActionPerformed
    }

    public void limpaTabelaSerie(JTable tabela) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        for (; model.getRowCount() > 0; model.removeRow(model.getRowCount() - 1));
    }
    
    public void imprimeTabelaSeries(ConjuntoSeries series, JTable tabela) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        int i = series.listaSeries().size();
        int j = 0;
        while (j <= i - 1) {
            int numS = series.getSerie(j).getSeguidores();
            String nome = series.getSerie(j).getTitulo();
            int numE=0;
            for(int k=0;k<=series.getSerie(k).getTemporadas().size();k++){
                numE+=series.getSerie(k).getTemporadas().get(k).listaEpisodios().size();
            }
            float nota = series.getSerie(j).calculaNota(series.getSerie(j).getNotas());
            Object[] row = {nome, numE, numS, nota};
            model.addRow(row);
            j++;
        }
    }
    
    public void atualizaTabelaSeries( ConjuntoSeries series,JTable tabela) {
        limpaTabelaSerie(tabela);
        imprimeTabelaSeries(series, tabela);
    }
    
    private void atualizaJson(ConjuntoSeries series) {
        BancoDeSeries s = new BancoDeSeries(series);
        try {
            s.escreveArquivo();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    public void limpaTabela(JTable tabela) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        for (; model.getRowCount() > 0; model.removeRow(model.getRowCount() - 1));
    }
    
    public void imprimeTabela(ConjuntoPerfis perfis, JTable tabela) {
        DefaultTableModel model = (DefaultTableModel) tabela.getModel();
        int i = perfis.listaPerfis().size();
        int j = 0;
        while (j <= i - 1) {
            int numS = perfis.getPerfil(j).getSeriesAssistidas().size();
            String nick = perfis.getPerfil(j).getNick();
            Object[] row = {nick, numS};
            model.addRow(row);
            j++;
        }
    }
    
    public void atualizaTabela( ConjuntoPerfis perfis,JTable tabela) {
        limpaTabela(tabela);
        imprimeTabela(perfis, tabela);
    }
    
    private void atualizaJson(ConjuntoPerfis perfis) {
        BancoDePerfis p = new BancoDePerfis(perfis);
        try {
            p.escreveArquivo();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAddPerfil;
    private javax.swing.JButton botaoExcluiPerfil;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JLabel curioCalorias;
    private javax.swing.JLabel curioFilme;
    private javax.swing.JLabel curioLivro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelBio;
    private javax.swing.JLabel labelNick;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNumEps;
    private javax.swing.JLabel labelNumHoras;
    private javax.swing.JLabel labelNumSeries;
    // End of variables declaration//GEN-END:variables
}
